services:
  db:
    image: postgres:16-alpine
    container_name: hochwasser-db
    restart: always
    environment:
      POSTGRES_USER: {$DB_USER}
      POSTGRES_PASSWORD: {$DB_PASSWORD}
      POSTGRES_DB: {$sh_hochwasser}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: